
CREATE USER dw_writer WITH PASSWORD '<A_DEFINIR>';
CREATE USER ia1_reader WITH PASSWORD '<A_DEFINIR>';

GRANT CONNECT ON DATABASE air_quality TO dw_writer;
GRANT CONNECT ON DATABASE air_quality TO ia1_reader;
GRANT USAGE ON SCHEMA public TO dw_writer;
GRANT USAGE ON SCHEMA public TO ia1_reader;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dw_writer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dw_writer;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ia1_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ia1_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO dw_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO dw_writer;
